# This is a basic workflow to help you get started with Actions

name: CI

on:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '13,33,53 * * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      
      # Runs a single command using the runners shell
      - name: update submodules
        run: |
          pwd
          git submodule update --init
          sudo apt install ffmpeg -y
          cd 'growlab-pics-greenhouse/#Bucket052021-01/'
          pwd
          ffmpeg -pattern_type glob -i './202*.jpg' ../latest#Bucket050221-01.gif
          cd ../..
          cd 'growlab-pics-windowsill-back/#Rocket062021-01/'
          pwd
          ffmpeg -pattern_type glob -i './202*.jpg' ../latestWindowSill.gif
          cd ../..
          
          
